version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: fastnuxt
      POSTGRES_PASSWORD: fastnuxtpass
      POSTGRES_DB: fastnuxtdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
