"""Add objectives and progress_updates tables

Revision ID: 8e595d257e90
Revises: 70c6f7ff50d3
Create Date: 2025-05-10 18:21:55.164428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e595d257e90'
down_revision: Union[str, None] = '70c6f7ff50d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objectives',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.Enum('ORGANIZATIONAL', 'DEPARTMENTAL', 'TEAM', 'INDIVIDUAL', name='objectivelevel'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('parent_objective_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'ON_TRACK', 'AT_RISK', 'DELAYED', 'ACHIEVED', 'ON_HOLD', 'CANCELLED', name='objectivestatus'), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='objectivepriority'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('target_completion_date', sa.Date(), nullable=False),
    sa.Column('actual_completion_date', sa.Date(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('last_updated_date', sa.DateTime(), nullable=False),
    sa.Column('alignment_statement', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('confidentiality', sa.Enum('PUBLIC', 'INTERNAL', 'RESTRICTED', name='objectiveconfidentiality'), nullable=True),
    sa.Column('strategic_perspective', sa.Enum('FINANCIAL', 'CUSTOMER', 'INTERNAL_PROCESS', 'LEARNING_GROWTH', name='objectivestrategicperspective'), nullable=True),
    sa.Column('review_cadence', sa.Enum('MONTHLY', 'QUARTERLY', 'BI_ANNUALLY', 'ANNUALLY', name='objectivereviewcadence'), nullable=True),
    sa.Column('last_review_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['parent_objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objectives_id'), 'objectives', ['id'], unique=False)
    op.create_table('progress_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=False),
    sa.Column('progress_date', sa.Date(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_updates_id'), 'progress_updates', ['id'], unique=False)
    op.create_index(op.f('ix_progress_updates_objective_id'), 'progress_updates', ['objective_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_updates_objective_id'), table_name='progress_updates')
    op.drop_index(op.f('ix_progress_updates_id'), table_name='progress_updates')
    op.drop_table('progress_updates')
    op.drop_index(op.f('ix_objectives_id'), table_name='objectives')
    op.drop_table('objectives')
    # ### end Alembic commands ###
